console.log "importing components..."
import "@dashkite/vellum"

import "./components/connect"
import "./components/sites"
import "./components/site"
import "./components/gadget"
import "./components/page/select"
import "./components/image/select"
import "./components/image/wayland-select"
import "./components/icon/select"
import "./components/fonts/select"
import "./components/colors/select"
import "./components/mode"

