page:
  - name
  - description
  - preview.url
  # icon, favicon
layout:
  - name
  - subtype
  - hints.orientation
  - hints.wrap
  - hints.justification
  - hints.alignment
  - hints.size
  - hints.width
  - hints.proximity
navigation: [ name, description ]
link: [ name, url, page ]
text: [ name, text ]
image: [ name, description, image.url ]
variant: [ name, hints.mode, hints.resolution, hints.device, image.url ]
icon: [ name, hints.style, hints.size, icon]
